spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/backend_challenge
    username: doodle
    password: d00D13
    driverClassName: org.postgresql.Driver
  jackson:
    default-property-inclusion: NON_NULL
    deserialization:
      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false
  application:
    name: scheduler
  redis:
    host: 172.20.0.31
    port: 6373
    cluster:
      nodes: localhost:6373,localhost:6374,localhost:6375,localhost:6376,localhost:6377,localhost:6378

server:
  tomcat:
    threads:
      max: 200
      min-spare: 10
    mbeanregistry:
      enabled: true
  servlet:
    context-path: /${spring.application.name}
  error:
    include-message: always

logging:
  level:
    ROOT: WARN
    org.apache.tomcat: INFO
    org.apache.catalina: INFO
    com.sun.xml: WARN
    javax.xml: WARN
    org.hibernate: ERROR
    org.springframework: WARN
    org.springframework.web: WARN
    feign.Logger: WARN
    com.doodle.backendchallenge: WARN